# Site settings
title: Meditation Research -SLIM
email: chhabr56@msu.edu
description: Exploring Neural Mechanisms of Contemplative Practices
baseurl: "/mantralab"
url: "https://sidc.github.io"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

# Collections configuration
collections:
  team:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/
  gallery:
    output: false
  videos:
    output: false

# Make collections available
defaults:
  - scope:
      path: ""
      type: "team"
    values:
      layout: default
  - scope:
      path: ""
      type: "publications"
    values:
      layout: default
  - scope:
      path: ""
    values:
      layout: default

# Exclude from build
exclude:
  - README.md
  - "*.ps1"
  - "*.old"
  - "*.backup"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor